// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cairn.proto

package cairnv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cairnv1 "github.com/geekgonecrazy/cairn/proto/cairnv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CairnServiceName is the fully-qualified name of the CairnService service.
	CairnServiceName = "cairn.v1.CairnService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CairnServiceSendEventProcedure is the fully-qualified name of the CairnService's SendEvent RPC.
	CairnServiceSendEventProcedure = "/cairn.v1.CairnService/SendEvent"
	// CairnServiceSyncProcedure is the fully-qualified name of the CairnService's Sync RPC.
	CairnServiceSyncProcedure = "/cairn.v1.CairnService/Sync"
	// CairnServiceHistoryProcedure is the fully-qualified name of the CairnService's History RPC.
	CairnServiceHistoryProcedure = "/cairn.v1.CairnService/History"
	// CairnServiceGetIdentityObjectProcedure is the fully-qualified name of the CairnService's
	// GetIdentityObject RPC.
	CairnServiceGetIdentityObjectProcedure = "/cairn.v1.CairnService/GetIdentityObject"
	// CairnServicePutIdentityObjectProcedure is the fully-qualified name of the CairnService's
	// PutIdentityObject RPC.
	CairnServicePutIdentityObjectProcedure = "/cairn.v1.CairnService/PutIdentityObject"
	// CairnServiceResolveSenderProcedure is the fully-qualified name of the CairnService's
	// ResolveSender RPC.
	CairnServiceResolveSenderProcedure = "/cairn.v1.CairnService/ResolveSender"
	// CairnServiceListRoomsProcedure is the fully-qualified name of the CairnService's ListRooms RPC.
	CairnServiceListRoomsProcedure = "/cairn.v1.CairnService/ListRooms"
	// CairnServiceListSpaceMembersProcedure is the fully-qualified name of the CairnService's
	// ListSpaceMembers RPC.
	CairnServiceListSpaceMembersProcedure = "/cairn.v1.CairnService/ListSpaceMembers"
	// CairnServiceListMemberDevicesProcedure is the fully-qualified name of the CairnService's
	// ListMemberDevices RPC.
	CairnServiceListMemberDevicesProcedure = "/cairn.v1.CairnService/ListMemberDevices"
	// CairnServiceRelayInfoProcedure is the fully-qualified name of the CairnService's RelayInfo RPC.
	CairnServiceRelayInfoProcedure = "/cairn.v1.CairnService/RelayInfo"
	// CairnServiceRedeemInviteProcedure is the fully-qualified name of the CairnService's RedeemInvite
	// RPC.
	CairnServiceRedeemInviteProcedure = "/cairn.v1.CairnService/RedeemInvite"
	// CairnServiceDirectoryProcedure is the fully-qualified name of the CairnService's Directory RPC.
	CairnServiceDirectoryProcedure = "/cairn.v1.CairnService/Directory"
)

// CairnServiceClient is a client for the cairn.v1.CairnService service.
type CairnServiceClient interface {
	SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error)
	Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error)
	History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error)
	GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error)
	PutIdentityObject(context.Context, *connect.Request[cairnv1.PutIdentityObjectRequest]) (*connect.Response[cairnv1.PutIdentityObjectResponse], error)
	ResolveSender(context.Context, *connect.Request[cairnv1.ResolveSenderRequest]) (*connect.Response[cairnv1.ResolveSenderResponse], error)
	ListRooms(context.Context, *connect.Request[cairnv1.ListRoomsRequest]) (*connect.Response[cairnv1.ListRoomsResponse], error)
	ListSpaceMembers(context.Context, *connect.Request[cairnv1.ListSpaceMembersRequest]) (*connect.Response[cairnv1.ListSpaceMembersResponse], error)
	ListMemberDevices(context.Context, *connect.Request[cairnv1.ListMemberDevicesRequest]) (*connect.Response[cairnv1.ListMemberDevicesResponse], error)
	// Relay access (slice 2) + directory (slice 3).
	RelayInfo(context.Context, *connect.Request[cairnv1.RelayInfoRequest]) (*connect.Response[cairnv1.RelayInfoResponse], error)
	RedeemInvite(context.Context, *connect.Request[cairnv1.RedeemInviteRequest]) (*connect.Response[cairnv1.RedeemInviteResponse], error)
	Directory(context.Context, *connect.Request[cairnv1.DirectoryRequest]) (*connect.Response[cairnv1.DirectoryResponse], error)
}

// NewCairnServiceClient constructs a client for the cairn.v1.CairnService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCairnServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CairnServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cairnServiceMethods := cairnv1.File_cairn_proto.Services().ByName("CairnService").Methods()
	return &cairnServiceClient{
		sendEvent: connect.NewClient[cairnv1.SendEventRequest, cairnv1.SendEventResponse](
			httpClient,
			baseURL+CairnServiceSendEventProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("SendEvent")),
			connect.WithClientOptions(opts...),
		),
		sync: connect.NewClient[cairnv1.SyncRequest, cairnv1.SyncResponse](
			httpClient,
			baseURL+CairnServiceSyncProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		history: connect.NewClient[cairnv1.HistoryRequest, cairnv1.HistoryResponse](
			httpClient,
			baseURL+CairnServiceHistoryProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("History")),
			connect.WithClientOptions(opts...),
		),
		getIdentityObject: connect.NewClient[cairnv1.GetIdentityObjectRequest, cairnv1.GetIdentityObjectResponse](
			httpClient,
			baseURL+CairnServiceGetIdentityObjectProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("GetIdentityObject")),
			connect.WithClientOptions(opts...),
		),
		putIdentityObject: connect.NewClient[cairnv1.PutIdentityObjectRequest, cairnv1.PutIdentityObjectResponse](
			httpClient,
			baseURL+CairnServicePutIdentityObjectProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("PutIdentityObject")),
			connect.WithClientOptions(opts...),
		),
		resolveSender: connect.NewClient[cairnv1.ResolveSenderRequest, cairnv1.ResolveSenderResponse](
			httpClient,
			baseURL+CairnServiceResolveSenderProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("ResolveSender")),
			connect.WithClientOptions(opts...),
		),
		listRooms: connect.NewClient[cairnv1.ListRoomsRequest, cairnv1.ListRoomsResponse](
			httpClient,
			baseURL+CairnServiceListRoomsProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("ListRooms")),
			connect.WithClientOptions(opts...),
		),
		listSpaceMembers: connect.NewClient[cairnv1.ListSpaceMembersRequest, cairnv1.ListSpaceMembersResponse](
			httpClient,
			baseURL+CairnServiceListSpaceMembersProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("ListSpaceMembers")),
			connect.WithClientOptions(opts...),
		),
		listMemberDevices: connect.NewClient[cairnv1.ListMemberDevicesRequest, cairnv1.ListMemberDevicesResponse](
			httpClient,
			baseURL+CairnServiceListMemberDevicesProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("ListMemberDevices")),
			connect.WithClientOptions(opts...),
		),
		relayInfo: connect.NewClient[cairnv1.RelayInfoRequest, cairnv1.RelayInfoResponse](
			httpClient,
			baseURL+CairnServiceRelayInfoProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("RelayInfo")),
			connect.WithClientOptions(opts...),
		),
		redeemInvite: connect.NewClient[cairnv1.RedeemInviteRequest, cairnv1.RedeemInviteResponse](
			httpClient,
			baseURL+CairnServiceRedeemInviteProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("RedeemInvite")),
			connect.WithClientOptions(opts...),
		),
		directory: connect.NewClient[cairnv1.DirectoryRequest, cairnv1.DirectoryResponse](
			httpClient,
			baseURL+CairnServiceDirectoryProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("Directory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cairnServiceClient implements CairnServiceClient.
type cairnServiceClient struct {
	sendEvent         *connect.Client[cairnv1.SendEventRequest, cairnv1.SendEventResponse]
	sync              *connect.Client[cairnv1.SyncRequest, cairnv1.SyncResponse]
	history           *connect.Client[cairnv1.HistoryRequest, cairnv1.HistoryResponse]
	getIdentityObject *connect.Client[cairnv1.GetIdentityObjectRequest, cairnv1.GetIdentityObjectResponse]
	putIdentityObject *connect.Client[cairnv1.PutIdentityObjectRequest, cairnv1.PutIdentityObjectResponse]
	resolveSender     *connect.Client[cairnv1.ResolveSenderRequest, cairnv1.ResolveSenderResponse]
	listRooms         *connect.Client[cairnv1.ListRoomsRequest, cairnv1.ListRoomsResponse]
	listSpaceMembers  *connect.Client[cairnv1.ListSpaceMembersRequest, cairnv1.ListSpaceMembersResponse]
	listMemberDevices *connect.Client[cairnv1.ListMemberDevicesRequest, cairnv1.ListMemberDevicesResponse]
	relayInfo         *connect.Client[cairnv1.RelayInfoRequest, cairnv1.RelayInfoResponse]
	redeemInvite      *connect.Client[cairnv1.RedeemInviteRequest, cairnv1.RedeemInviteResponse]
	directory         *connect.Client[cairnv1.DirectoryRequest, cairnv1.DirectoryResponse]
}

// SendEvent calls cairn.v1.CairnService.SendEvent.
func (c *cairnServiceClient) SendEvent(ctx context.Context, req *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error) {
	return c.sendEvent.CallUnary(ctx, req)
}

// Sync calls cairn.v1.CairnService.Sync.
func (c *cairnServiceClient) Sync(ctx context.Context, req *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error) {
	return c.sync.CallUnary(ctx, req)
}

// History calls cairn.v1.CairnService.History.
func (c *cairnServiceClient) History(ctx context.Context, req *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error) {
	return c.history.CallUnary(ctx, req)
}

// GetIdentityObject calls cairn.v1.CairnService.GetIdentityObject.
func (c *cairnServiceClient) GetIdentityObject(ctx context.Context, req *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error) {
	return c.getIdentityObject.CallUnary(ctx, req)
}

// PutIdentityObject calls cairn.v1.CairnService.PutIdentityObject.
func (c *cairnServiceClient) PutIdentityObject(ctx context.Context, req *connect.Request[cairnv1.PutIdentityObjectRequest]) (*connect.Response[cairnv1.PutIdentityObjectResponse], error) {
	return c.putIdentityObject.CallUnary(ctx, req)
}

// ResolveSender calls cairn.v1.CairnService.ResolveSender.
func (c *cairnServiceClient) ResolveSender(ctx context.Context, req *connect.Request[cairnv1.ResolveSenderRequest]) (*connect.Response[cairnv1.ResolveSenderResponse], error) {
	return c.resolveSender.CallUnary(ctx, req)
}

// ListRooms calls cairn.v1.CairnService.ListRooms.
func (c *cairnServiceClient) ListRooms(ctx context.Context, req *connect.Request[cairnv1.ListRoomsRequest]) (*connect.Response[cairnv1.ListRoomsResponse], error) {
	return c.listRooms.CallUnary(ctx, req)
}

// ListSpaceMembers calls cairn.v1.CairnService.ListSpaceMembers.
func (c *cairnServiceClient) ListSpaceMembers(ctx context.Context, req *connect.Request[cairnv1.ListSpaceMembersRequest]) (*connect.Response[cairnv1.ListSpaceMembersResponse], error) {
	return c.listSpaceMembers.CallUnary(ctx, req)
}

// ListMemberDevices calls cairn.v1.CairnService.ListMemberDevices.
func (c *cairnServiceClient) ListMemberDevices(ctx context.Context, req *connect.Request[cairnv1.ListMemberDevicesRequest]) (*connect.Response[cairnv1.ListMemberDevicesResponse], error) {
	return c.listMemberDevices.CallUnary(ctx, req)
}

// RelayInfo calls cairn.v1.CairnService.RelayInfo.
func (c *cairnServiceClient) RelayInfo(ctx context.Context, req *connect.Request[cairnv1.RelayInfoRequest]) (*connect.Response[cairnv1.RelayInfoResponse], error) {
	return c.relayInfo.CallUnary(ctx, req)
}

// RedeemInvite calls cairn.v1.CairnService.RedeemInvite.
func (c *cairnServiceClient) RedeemInvite(ctx context.Context, req *connect.Request[cairnv1.RedeemInviteRequest]) (*connect.Response[cairnv1.RedeemInviteResponse], error) {
	return c.redeemInvite.CallUnary(ctx, req)
}

// Directory calls cairn.v1.CairnService.Directory.
func (c *cairnServiceClient) Directory(ctx context.Context, req *connect.Request[cairnv1.DirectoryRequest]) (*connect.Response[cairnv1.DirectoryResponse], error) {
	return c.directory.CallUnary(ctx, req)
}

// CairnServiceHandler is an implementation of the cairn.v1.CairnService service.
type CairnServiceHandler interface {
	SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error)
	Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error)
	History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error)
	GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error)
	PutIdentityObject(context.Context, *connect.Request[cairnv1.PutIdentityObjectRequest]) (*connect.Response[cairnv1.PutIdentityObjectResponse], error)
	ResolveSender(context.Context, *connect.Request[cairnv1.ResolveSenderRequest]) (*connect.Response[cairnv1.ResolveSenderResponse], error)
	ListRooms(context.Context, *connect.Request[cairnv1.ListRoomsRequest]) (*connect.Response[cairnv1.ListRoomsResponse], error)
	ListSpaceMembers(context.Context, *connect.Request[cairnv1.ListSpaceMembersRequest]) (*connect.Response[cairnv1.ListSpaceMembersResponse], error)
	ListMemberDevices(context.Context, *connect.Request[cairnv1.ListMemberDevicesRequest]) (*connect.Response[cairnv1.ListMemberDevicesResponse], error)
	// Relay access (slice 2) + directory (slice 3).
	RelayInfo(context.Context, *connect.Request[cairnv1.RelayInfoRequest]) (*connect.Response[cairnv1.RelayInfoResponse], error)
	RedeemInvite(context.Context, *connect.Request[cairnv1.RedeemInviteRequest]) (*connect.Response[cairnv1.RedeemInviteResponse], error)
	Directory(context.Context, *connect.Request[cairnv1.DirectoryRequest]) (*connect.Response[cairnv1.DirectoryResponse], error)
}

// NewCairnServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCairnServiceHandler(svc CairnServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cairnServiceMethods := cairnv1.File_cairn_proto.Services().ByName("CairnService").Methods()
	cairnServiceSendEventHandler := connect.NewUnaryHandler(
		CairnServiceSendEventProcedure,
		svc.SendEvent,
		connect.WithSchema(cairnServiceMethods.ByName("SendEvent")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceSyncHandler := connect.NewUnaryHandler(
		CairnServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(cairnServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceHistoryHandler := connect.NewUnaryHandler(
		CairnServiceHistoryProcedure,
		svc.History,
		connect.WithSchema(cairnServiceMethods.ByName("History")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceGetIdentityObjectHandler := connect.NewUnaryHandler(
		CairnServiceGetIdentityObjectProcedure,
		svc.GetIdentityObject,
		connect.WithSchema(cairnServiceMethods.ByName("GetIdentityObject")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServicePutIdentityObjectHandler := connect.NewUnaryHandler(
		CairnServicePutIdentityObjectProcedure,
		svc.PutIdentityObject,
		connect.WithSchema(cairnServiceMethods.ByName("PutIdentityObject")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceResolveSenderHandler := connect.NewUnaryHandler(
		CairnServiceResolveSenderProcedure,
		svc.ResolveSender,
		connect.WithSchema(cairnServiceMethods.ByName("ResolveSender")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceListRoomsHandler := connect.NewUnaryHandler(
		CairnServiceListRoomsProcedure,
		svc.ListRooms,
		connect.WithSchema(cairnServiceMethods.ByName("ListRooms")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceListSpaceMembersHandler := connect.NewUnaryHandler(
		CairnServiceListSpaceMembersProcedure,
		svc.ListSpaceMembers,
		connect.WithSchema(cairnServiceMethods.ByName("ListSpaceMembers")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceListMemberDevicesHandler := connect.NewUnaryHandler(
		CairnServiceListMemberDevicesProcedure,
		svc.ListMemberDevices,
		connect.WithSchema(cairnServiceMethods.ByName("ListMemberDevices")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceRelayInfoHandler := connect.NewUnaryHandler(
		CairnServiceRelayInfoProcedure,
		svc.RelayInfo,
		connect.WithSchema(cairnServiceMethods.ByName("RelayInfo")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceRedeemInviteHandler := connect.NewUnaryHandler(
		CairnServiceRedeemInviteProcedure,
		svc.RedeemInvite,
		connect.WithSchema(cairnServiceMethods.ByName("RedeemInvite")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceDirectoryHandler := connect.NewUnaryHandler(
		CairnServiceDirectoryProcedure,
		svc.Directory,
		connect.WithSchema(cairnServiceMethods.ByName("Directory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cairn.v1.CairnService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CairnServiceSendEventProcedure:
			cairnServiceSendEventHandler.ServeHTTP(w, r)
		case CairnServiceSyncProcedure:
			cairnServiceSyncHandler.ServeHTTP(w, r)
		case CairnServiceHistoryProcedure:
			cairnServiceHistoryHandler.ServeHTTP(w, r)
		case CairnServiceGetIdentityObjectProcedure:
			cairnServiceGetIdentityObjectHandler.ServeHTTP(w, r)
		case CairnServicePutIdentityObjectProcedure:
			cairnServicePutIdentityObjectHandler.ServeHTTP(w, r)
		case CairnServiceResolveSenderProcedure:
			cairnServiceResolveSenderHandler.ServeHTTP(w, r)
		case CairnServiceListRoomsProcedure:
			cairnServiceListRoomsHandler.ServeHTTP(w, r)
		case CairnServiceListSpaceMembersProcedure:
			cairnServiceListSpaceMembersHandler.ServeHTTP(w, r)
		case CairnServiceListMemberDevicesProcedure:
			cairnServiceListMemberDevicesHandler.ServeHTTP(w, r)
		case CairnServiceRelayInfoProcedure:
			cairnServiceRelayInfoHandler.ServeHTTP(w, r)
		case CairnServiceRedeemInviteProcedure:
			cairnServiceRedeemInviteHandler.ServeHTTP(w, r)
		case CairnServiceDirectoryProcedure:
			cairnServiceDirectoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCairnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCairnServiceHandler struct{}

func (UnimplementedCairnServiceHandler) SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.SendEvent is not implemented"))
}

func (UnimplementedCairnServiceHandler) Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.Sync is not implemented"))
}

func (UnimplementedCairnServiceHandler) History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.History is not implemented"))
}

func (UnimplementedCairnServiceHandler) GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.GetIdentityObject is not implemented"))
}

func (UnimplementedCairnServiceHandler) PutIdentityObject(context.Context, *connect.Request[cairnv1.PutIdentityObjectRequest]) (*connect.Response[cairnv1.PutIdentityObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.PutIdentityObject is not implemented"))
}

func (UnimplementedCairnServiceHandler) ResolveSender(context.Context, *connect.Request[cairnv1.ResolveSenderRequest]) (*connect.Response[cairnv1.ResolveSenderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.ResolveSender is not implemented"))
}

func (UnimplementedCairnServiceHandler) ListRooms(context.Context, *connect.Request[cairnv1.ListRoomsRequest]) (*connect.Response[cairnv1.ListRoomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.ListRooms is not implemented"))
}

func (UnimplementedCairnServiceHandler) ListSpaceMembers(context.Context, *connect.Request[cairnv1.ListSpaceMembersRequest]) (*connect.Response[cairnv1.ListSpaceMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.ListSpaceMembers is not implemented"))
}

func (UnimplementedCairnServiceHandler) ListMemberDevices(context.Context, *connect.Request[cairnv1.ListMemberDevicesRequest]) (*connect.Response[cairnv1.ListMemberDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.ListMemberDevices is not implemented"))
}

func (UnimplementedCairnServiceHandler) RelayInfo(context.Context, *connect.Request[cairnv1.RelayInfoRequest]) (*connect.Response[cairnv1.RelayInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.RelayInfo is not implemented"))
}

func (UnimplementedCairnServiceHandler) RedeemInvite(context.Context, *connect.Request[cairnv1.RedeemInviteRequest]) (*connect.Response[cairnv1.RedeemInviteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.RedeemInvite is not implemented"))
}

func (UnimplementedCairnServiceHandler) Directory(context.Context, *connect.Request[cairnv1.DirectoryRequest]) (*connect.Response[cairnv1.DirectoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.Directory is not implemented"))
}
