// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cairn.proto

package cairnv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cairnv1 "github.com/geekgonecrazy/cairn/proto/cairnv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CairnServiceName is the fully-qualified name of the CairnService service.
	CairnServiceName = "cairn.v1.CairnService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CairnServiceSendEventProcedure is the fully-qualified name of the CairnService's SendEvent RPC.
	CairnServiceSendEventProcedure = "/cairn.v1.CairnService/SendEvent"
	// CairnServiceSyncProcedure is the fully-qualified name of the CairnService's Sync RPC.
	CairnServiceSyncProcedure = "/cairn.v1.CairnService/Sync"
	// CairnServiceHistoryProcedure is the fully-qualified name of the CairnService's History RPC.
	CairnServiceHistoryProcedure = "/cairn.v1.CairnService/History"
	// CairnServiceGetIdentityObjectProcedure is the fully-qualified name of the CairnService's
	// GetIdentityObject RPC.
	CairnServiceGetIdentityObjectProcedure = "/cairn.v1.CairnService/GetIdentityObject"
)

// CairnServiceClient is a client for the cairn.v1.CairnService service.
type CairnServiceClient interface {
	SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error)
	Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error)
	History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error)
	GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error)
}

// NewCairnServiceClient constructs a client for the cairn.v1.CairnService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCairnServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CairnServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cairnServiceMethods := cairnv1.File_cairn_proto.Services().ByName("CairnService").Methods()
	return &cairnServiceClient{
		sendEvent: connect.NewClient[cairnv1.SendEventRequest, cairnv1.SendEventResponse](
			httpClient,
			baseURL+CairnServiceSendEventProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("SendEvent")),
			connect.WithClientOptions(opts...),
		),
		sync: connect.NewClient[cairnv1.SyncRequest, cairnv1.SyncResponse](
			httpClient,
			baseURL+CairnServiceSyncProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		history: connect.NewClient[cairnv1.HistoryRequest, cairnv1.HistoryResponse](
			httpClient,
			baseURL+CairnServiceHistoryProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("History")),
			connect.WithClientOptions(opts...),
		),
		getIdentityObject: connect.NewClient[cairnv1.GetIdentityObjectRequest, cairnv1.GetIdentityObjectResponse](
			httpClient,
			baseURL+CairnServiceGetIdentityObjectProcedure,
			connect.WithSchema(cairnServiceMethods.ByName("GetIdentityObject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cairnServiceClient implements CairnServiceClient.
type cairnServiceClient struct {
	sendEvent         *connect.Client[cairnv1.SendEventRequest, cairnv1.SendEventResponse]
	sync              *connect.Client[cairnv1.SyncRequest, cairnv1.SyncResponse]
	history           *connect.Client[cairnv1.HistoryRequest, cairnv1.HistoryResponse]
	getIdentityObject *connect.Client[cairnv1.GetIdentityObjectRequest, cairnv1.GetIdentityObjectResponse]
}

// SendEvent calls cairn.v1.CairnService.SendEvent.
func (c *cairnServiceClient) SendEvent(ctx context.Context, req *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error) {
	return c.sendEvent.CallUnary(ctx, req)
}

// Sync calls cairn.v1.CairnService.Sync.
func (c *cairnServiceClient) Sync(ctx context.Context, req *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error) {
	return c.sync.CallUnary(ctx, req)
}

// History calls cairn.v1.CairnService.History.
func (c *cairnServiceClient) History(ctx context.Context, req *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error) {
	return c.history.CallUnary(ctx, req)
}

// GetIdentityObject calls cairn.v1.CairnService.GetIdentityObject.
func (c *cairnServiceClient) GetIdentityObject(ctx context.Context, req *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error) {
	return c.getIdentityObject.CallUnary(ctx, req)
}

// CairnServiceHandler is an implementation of the cairn.v1.CairnService service.
type CairnServiceHandler interface {
	SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error)
	Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error)
	History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error)
	GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error)
}

// NewCairnServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCairnServiceHandler(svc CairnServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cairnServiceMethods := cairnv1.File_cairn_proto.Services().ByName("CairnService").Methods()
	cairnServiceSendEventHandler := connect.NewUnaryHandler(
		CairnServiceSendEventProcedure,
		svc.SendEvent,
		connect.WithSchema(cairnServiceMethods.ByName("SendEvent")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceSyncHandler := connect.NewUnaryHandler(
		CairnServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(cairnServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceHistoryHandler := connect.NewUnaryHandler(
		CairnServiceHistoryProcedure,
		svc.History,
		connect.WithSchema(cairnServiceMethods.ByName("History")),
		connect.WithHandlerOptions(opts...),
	)
	cairnServiceGetIdentityObjectHandler := connect.NewUnaryHandler(
		CairnServiceGetIdentityObjectProcedure,
		svc.GetIdentityObject,
		connect.WithSchema(cairnServiceMethods.ByName("GetIdentityObject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cairn.v1.CairnService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CairnServiceSendEventProcedure:
			cairnServiceSendEventHandler.ServeHTTP(w, r)
		case CairnServiceSyncProcedure:
			cairnServiceSyncHandler.ServeHTTP(w, r)
		case CairnServiceHistoryProcedure:
			cairnServiceHistoryHandler.ServeHTTP(w, r)
		case CairnServiceGetIdentityObjectProcedure:
			cairnServiceGetIdentityObjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCairnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCairnServiceHandler struct{}

func (UnimplementedCairnServiceHandler) SendEvent(context.Context, *connect.Request[cairnv1.SendEventRequest]) (*connect.Response[cairnv1.SendEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.SendEvent is not implemented"))
}

func (UnimplementedCairnServiceHandler) Sync(context.Context, *connect.Request[cairnv1.SyncRequest]) (*connect.Response[cairnv1.SyncResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.Sync is not implemented"))
}

func (UnimplementedCairnServiceHandler) History(context.Context, *connect.Request[cairnv1.HistoryRequest]) (*connect.Response[cairnv1.HistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.History is not implemented"))
}

func (UnimplementedCairnServiceHandler) GetIdentityObject(context.Context, *connect.Request[cairnv1.GetIdentityObjectRequest]) (*connect.Response[cairnv1.GetIdentityObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cairn.v1.CairnService.GetIdentityObject is not implemented"))
}
