// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cairn.proto

package cairnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// Chat
	EventType_CHAT     EventType = 1
	EventType_FILE_REF EventType = 2
	EventType_PRESENCE EventType = 3
	EventType_REACTION EventType = 4
	EventType_EDIT     EventType = 5
	EventType_DELETE   EventType = 6
	// Agent
	EventType_TASK_REQUEST EventType = 10
	EventType_TASK_UPDATE  EventType = 11
	EventType_NOTIFY       EventType = 12
	EventType_COMMAND      EventType = 13
	// Authority
	EventType_APPROVAL_REQUEST  EventType = 20
	EventType_APPROVAL_GRANT    EventType = 21
	EventType_APPROVAL_DENY     EventType = 22
	EventType_CREDENTIAL_MINTED EventType = 23
	// Inlay UI
	EventType_INLAY        EventType = 30
	EventType_INLAY_UPDATE EventType = 31
	EventType_INLAY_UNPIN  EventType = 32
	EventType_INTERACTION  EventType = 33
	// Call (signaling only; live WebRTC lives in the video component)
	EventType_SIGNALING_OFFER  EventType = 40
	EventType_SIGNALING_ANSWER EventType = 41
	EventType_SIGNALING_ICE    EventType = 42
	EventType_CALL_RING        EventType = 43
	EventType_CALL_BYE         EventType = 44
	// Room state
	EventType_MEMBER_ADD      EventType = 50
	EventType_MEMBER_REMOVE   EventType = 51
	EventType_ROOM_KEY_ROTATE EventType = 52
	EventType_SPACE_CREATE    EventType = 53
	EventType_SPACE_UPDATE    EventType = 54
	EventType_ROOM_CREATE     EventType = 55
	// Identity (live in the household identity log; fetched by hash)
	EventType_IDENTITY_ATTESTATION EventType = 60
	EventType_DEVICE_DELEGATION    EventType = 61
	EventType_DEVICE_REVOKE        EventType = 62
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "CHAT",
		2:  "FILE_REF",
		3:  "PRESENCE",
		4:  "REACTION",
		5:  "EDIT",
		6:  "DELETE",
		10: "TASK_REQUEST",
		11: "TASK_UPDATE",
		12: "NOTIFY",
		13: "COMMAND",
		20: "APPROVAL_REQUEST",
		21: "APPROVAL_GRANT",
		22: "APPROVAL_DENY",
		23: "CREDENTIAL_MINTED",
		30: "INLAY",
		31: "INLAY_UPDATE",
		32: "INLAY_UNPIN",
		33: "INTERACTION",
		40: "SIGNALING_OFFER",
		41: "SIGNALING_ANSWER",
		42: "SIGNALING_ICE",
		43: "CALL_RING",
		44: "CALL_BYE",
		50: "MEMBER_ADD",
		51: "MEMBER_REMOVE",
		52: "ROOM_KEY_ROTATE",
		53: "SPACE_CREATE",
		54: "SPACE_UPDATE",
		55: "ROOM_CREATE",
		60: "IDENTITY_ATTESTATION",
		61: "DEVICE_DELEGATION",
		62: "DEVICE_REVOKE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"CHAT":                   1,
		"FILE_REF":               2,
		"PRESENCE":               3,
		"REACTION":               4,
		"EDIT":                   5,
		"DELETE":                 6,
		"TASK_REQUEST":           10,
		"TASK_UPDATE":            11,
		"NOTIFY":                 12,
		"COMMAND":                13,
		"APPROVAL_REQUEST":       20,
		"APPROVAL_GRANT":         21,
		"APPROVAL_DENY":          22,
		"CREDENTIAL_MINTED":      23,
		"INLAY":                  30,
		"INLAY_UPDATE":           31,
		"INLAY_UNPIN":            32,
		"INTERACTION":            33,
		"SIGNALING_OFFER":        40,
		"SIGNALING_ANSWER":       41,
		"SIGNALING_ICE":          42,
		"CALL_RING":              43,
		"CALL_BYE":               44,
		"MEMBER_ADD":             50,
		"MEMBER_REMOVE":          51,
		"ROOM_KEY_ROTATE":        52,
		"SPACE_CREATE":           53,
		"SPACE_UPDATE":           54,
		"ROOM_CREATE":            55,
		"IDENTITY_ATTESTATION":   60,
		"DEVICE_DELEGATION":      61,
		"DEVICE_REVOKE":          62,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_cairn_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{0}
}

// Per-message transport override the sending client may attach out-of-band
// (not part of the signed event). See PROTOCOL.md §Transport.
type TransportHint int32

const (
	TransportHint_TRANSPORT_HINT_UNSPECIFIED TransportHint = 0 // = "any"
	TransportHint_TRANSPORT_HINT_LAN         TransportHint = 1
	TransportHint_TRANSPORT_HINT_MESH        TransportHint = 2
	TransportHint_TRANSPORT_HINT_BLE         TransportHint = 3
	TransportHint_TRANSPORT_HINT_ALL         TransportHint = 4
)

// Enum value maps for TransportHint.
var (
	TransportHint_name = map[int32]string{
		0: "TRANSPORT_HINT_UNSPECIFIED",
		1: "TRANSPORT_HINT_LAN",
		2: "TRANSPORT_HINT_MESH",
		3: "TRANSPORT_HINT_BLE",
		4: "TRANSPORT_HINT_ALL",
	}
	TransportHint_value = map[string]int32{
		"TRANSPORT_HINT_UNSPECIFIED": 0,
		"TRANSPORT_HINT_LAN":         1,
		"TRANSPORT_HINT_MESH":        2,
		"TRANSPORT_HINT_BLE":         3,
		"TRANSPORT_HINT_ALL":         4,
	}
)

func (x TransportHint) Enum() *TransportHint {
	p := new(TransportHint)
	*p = x
	return p
}

func (x TransportHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportHint) Descriptor() protoreflect.EnumDescriptor {
	return file_cairn_proto_enumTypes[1].Descriptor()
}

func (TransportHint) Type() protoreflect.EnumType {
	return &file_cairn_proto_enumTypes[1]
}

func (x TransportHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportHint.Descriptor instead.
func (TransportHint) EnumDescriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BLAKE3-256 of the canonical signed content (see PROTOCOL.md §Event). The
	// content address of this event; also its identity for parents/reply/react.
	EventId []byte `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Ed25519 public key of the *device* or *session* key that signed this event.
	// Verified back to a member root → household root via the identity log.
	SenderPub []byte `protobuf:"bytes,2,opt,name=sender_pub,json=senderPub,proto3" json:"sender_pub,omitempty"`
	RoomId    []byte `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Sender wall-clock, unix milliseconds. Advisory only — ordering is the
	// causal DAG (`parents`) with a deterministic tiebreak, never `ts`.
	Ts int64 `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	// event_ids the sender had already seen when it created this event (the
	// causal heads). This is the SYNC structure — not the semantic `reply_to`.
	Parents [][]byte  `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	Type    EventType `protobuf:"varint,6,opt,name=type,proto3,enum=cairn.v1.EventType" json:"type,omitempty"`
	// CBOR, encrypted under the room key. Framed as:
	//
	//	uvarint(key_epoch) || nonce(12) || AES-256-GCM(ciphertext||tag)
	//
	// AAD = sender_pub || room_id || ts(le64) || type. key_epoch 0 = not
	// room-encrypted (identity/room-state events carry their own scheme).
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Ed25519 by `sender_pub` over `event_id` (which is itself the BLAKE3 of the
	// canonical content). For passkey-signed authority events this is the
	// WebAuthn signature envelope instead — see PROTOCOL.md §Identity.
	Sig []byte `protobuf:"bytes,8,opt,name=sig,proto3" json:"sig,omitempty"`
	// NOT signed, NOT hashed, NOT stored as canonical: the transport this copy
	// arrived on (populated by the receiver for reachability learning).
	ArrivedVia    string `protobuf:"bytes,15,opt,name=arrived_via,json=arrivedVia,proto3" json:"arrived_via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cairn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *Event) GetSenderPub() []byte {
	if x != nil {
		return x.SenderPub
	}
	return nil
}

func (x *Event) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetParents() [][]byte {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Event) GetArrivedVia() string {
	if x != nil {
		return x.ArrivedVia
	}
	return ""
}

type SendEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Hint          TransportHint          `protobuf:"varint,2,opt,name=hint,proto3,enum=cairn.v1.TransportHint" json:"hint,omitempty"` // optional per-message override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventRequest) Reset() {
	*x = SendEventRequest{}
	mi := &file_cairn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventRequest) ProtoMessage() {}

func (x *SendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventRequest.ProtoReflect.Descriptor instead.
func (*SendEventRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{1}
}

func (x *SendEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SendEventRequest) GetHint() TransportHint {
	if x != nil {
		return x.Hint
	}
	return TransportHint_TRANSPORT_HINT_UNSPECIFIED
}

type SendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       []byte                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventResponse) Reset() {
	*x = SendEventResponse{}
	mi := &file_cairn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventResponse) ProtoMessage() {}

func (x *SendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventResponse.ProtoReflect.Descriptor instead.
func (*SendEventResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{2}
}

func (x *SendEventResponse) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

// Frontier sync: the client sends the heads it has for a room; the server
// returns the subgraph the client is missing, plus its own heads so the client
// can compute what to push back. This is the per-peer delivery cursor.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        []byte                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	HaveHeads     [][]byte               `protobuf:"bytes,2,rep,name=have_heads,json=haveHeads,proto3" json:"have_heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_cairn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *SyncRequest) GetHaveHeads() [][]byte {
	if x != nil {
		return x.HaveHeads
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missing       []*Event               `protobuf:"bytes,1,rep,name=missing,proto3" json:"missing,omitempty"` // events the client lacked, best-effort causal order
	Heads         [][]byte               `protobuf:"bytes,2,rep,name=heads,proto3" json:"heads,omitempty"`     // server's current heads for the room
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_cairn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetMissing() []*Event {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *SyncResponse) GetHeads() [][]byte {
	if x != nil {
		return x.Heads
	}
	return nil
}

// Backfill older history by walking parents from a known event.
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        []byte                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Before        []byte                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"` // event_id to walk back from (empty = from heads)
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_cairn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryRequest) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *HistoryRequest) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *HistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_cairn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Fetch an identity-log object (attestation / delegation / revoke) by hash the
// first time a client meets an unknown sender.
type GetIdentityObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityObjectRequest) Reset() {
	*x = GetIdentityObjectRequest{}
	mi := &file_cairn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityObjectRequest) ProtoMessage() {}

func (x *GetIdentityObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityObjectRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityObjectRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{7}
}

func (x *GetIdentityObjectRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetIdentityObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cbor          []byte                 `protobuf:"bytes,1,opt,name=cbor,proto3" json:"cbor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityObjectResponse) Reset() {
	*x = GetIdentityObjectResponse{}
	mi := &file_cairn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityObjectResponse) ProtoMessage() {}

func (x *GetIdentityObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityObjectResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityObjectResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{8}
}

func (x *GetIdentityObjectResponse) GetCbor() []byte {
	if x != nil {
		return x.Cbor
	}
	return nil
}

// Publish an identity-log object. The server VERIFIES the signature before
// storing; it never mints or vouches for identity, it only carries and serves
// what already verifies on its own.
type PutIdentityObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cbor          []byte                 `protobuf:"bytes,1,opt,name=cbor,proto3" json:"cbor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutIdentityObjectRequest) Reset() {
	*x = PutIdentityObjectRequest{}
	mi := &file_cairn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutIdentityObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIdentityObjectRequest) ProtoMessage() {}

func (x *PutIdentityObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIdentityObjectRequest.ProtoReflect.Descriptor instead.
func (*PutIdentityObjectRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{9}
}

func (x *PutIdentityObjectRequest) GetCbor() []byte {
	if x != nil {
		return x.Cbor
	}
	return nil
}

type PutIdentityObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutIdentityObjectResponse) Reset() {
	*x = PutIdentityObjectResponse{}
	mi := &file_cairn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutIdentityObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIdentityObjectResponse) ProtoMessage() {}

func (x *PutIdentityObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIdentityObjectResponse.ProtoReflect.Descriptor instead.
func (*PutIdentityObjectResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{10}
}

func (x *PutIdentityObjectResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Resolve a sender key to the identity-log objects that place it.
//
// GetIdentityObject is keyed by HASH, but a client meeting an unknown sender
// holds only its PUBKEY and has no way to learn the hash — so hash-only lookup
// cannot bootstrap. This returns the whole chain for a sender key in one round
// trip: session delegation (if any), device delegation, attestation, and any
// revoke. Each object is independently signed, so the client verifies them
// itself and the server stays untrusted.
// A room/space the caller is a member of. Rooms are NOT pre-seeded: a household
// starts empty and every room exists because someone created it (ROOM_CREATE).
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        []byte                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SpaceId       []byte                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_cairn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{11}
}

func (x *RoomInfo) GetRoomId() []byte {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *RoomInfo) GetSpaceId() []byte {
	if x != nil {
		return x.SpaceId
	}
	return nil
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SpaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       []byte                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceInfo) Reset() {
	*x = SpaceInfo{}
	mi := &file_cairn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfo) ProtoMessage() {}

func (x *SpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfo.ProtoReflect.Descriptor instead.
func (*SpaceInfo) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{12}
}

func (x *SpaceInfo) GetSpaceId() []byte {
	if x != nil {
		return x.SpaceId
	}
	return nil
}

func (x *SpaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Rooms visible to member_pub — i.e. rooms it has been admitted to. Membership
// is a property of the MEMBER ROOT, not a device or session key.
type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberPub     []byte                 `protobuf:"bytes,1,opt,name=member_pub,json=memberPub,proto3" json:"member_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_cairn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{13}
}

func (x *ListRoomsRequest) GetMemberPub() []byte {
	if x != nil {
		return x.MemberPub
	}
	return nil
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Spaces        []*SpaceInfo           `protobuf:"bytes,2,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_cairn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{14}
}

func (x *ListRoomsResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetSpaces() []*SpaceInfo {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type ResolveSenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderPub     []byte                 `protobuf:"bytes,1,opt,name=sender_pub,json=senderPub,proto3" json:"sender_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSenderRequest) Reset() {
	*x = ResolveSenderRequest{}
	mi := &file_cairn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSenderRequest) ProtoMessage() {}

func (x *ResolveSenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSenderRequest.ProtoReflect.Descriptor instead.
func (*ResolveSenderRequest) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveSenderRequest) GetSenderPub() []byte {
	if x != nil {
		return x.SenderPub
	}
	return nil
}

type ResolveSenderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionDelegation []byte                 `protobuf:"bytes,1,opt,name=session_delegation,json=sessionDelegation,proto3" json:"session_delegation,omitempty"` // CBOR, empty if the sender is a device key
	DeviceDelegation  []byte                 `protobuf:"bytes,2,opt,name=device_delegation,json=deviceDelegation,proto3" json:"device_delegation,omitempty"`    // CBOR, empty if unknown
	Attestation       []byte                 `protobuf:"bytes,3,opt,name=attestation,proto3" json:"attestation,omitempty"`                                      // CBOR, empty if unknown
	DeviceRevoke      []byte                 `protobuf:"bytes,4,opt,name=device_revoke,json=deviceRevoke,proto3" json:"device_revoke,omitempty"`                // CBOR, empty if not revoked
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveSenderResponse) Reset() {
	*x = ResolveSenderResponse{}
	mi := &file_cairn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSenderResponse) ProtoMessage() {}

func (x *ResolveSenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSenderResponse.ProtoReflect.Descriptor instead.
func (*ResolveSenderResponse) Descriptor() ([]byte, []int) {
	return file_cairn_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveSenderResponse) GetSessionDelegation() []byte {
	if x != nil {
		return x.SessionDelegation
	}
	return nil
}

func (x *ResolveSenderResponse) GetDeviceDelegation() []byte {
	if x != nil {
		return x.DeviceDelegation
	}
	return nil
}

func (x *ResolveSenderResponse) GetAttestation() []byte {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *ResolveSenderResponse) GetDeviceRevoke() []byte {
	if x != nil {
		return x.DeviceRevoke
	}
	return nil
}

var File_cairn_proto protoreflect.FileDescriptor

const file_cairn_proto_rawDesc = "" +
	"\n" +
	"\vcairn.proto\x12\bcairn.v1\"\xfa\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12\x1d\n" +
	"\n" +
	"sender_pub\x18\x02 \x01(\fR\tsenderPub\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\fR\x06roomId\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\x12\x18\n" +
	"\aparents\x18\x05 \x03(\fR\aparents\x12'\n" +
	"\x04type\x18\x06 \x01(\x0e2\x13.cairn.v1.EventTypeR\x04type\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x10\n" +
	"\x03sig\x18\b \x01(\fR\x03sig\x12\x1f\n" +
	"\varrived_via\x18\x0f \x01(\tR\n" +
	"arrivedVia\"f\n" +
	"\x10SendEventRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.cairn.v1.EventR\x05event\x12+\n" +
	"\x04hint\x18\x02 \x01(\x0e2\x17.cairn.v1.TransportHintR\x04hint\".\n" +
	"\x11SendEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\"E\n" +
	"\vSyncRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\fR\x06roomId\x12\x1d\n" +
	"\n" +
	"have_heads\x18\x02 \x03(\fR\thaveHeads\"O\n" +
	"\fSyncResponse\x12)\n" +
	"\amissing\x18\x01 \x03(\v2\x0f.cairn.v1.EventR\amissing\x12\x14\n" +
	"\x05heads\x18\x02 \x03(\fR\x05heads\"W\n" +
	"\x0eHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\fR\x06roomId\x12\x16\n" +
	"\x06before\x18\x02 \x01(\fR\x06before\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\":\n" +
	"\x0fHistoryResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.cairn.v1.EventR\x06events\".\n" +
	"\x18GetIdentityObjectRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"/\n" +
	"\x19GetIdentityObjectResponse\x12\x12\n" +
	"\x04cbor\x18\x01 \x01(\fR\x04cbor\".\n" +
	"\x18PutIdentityObjectRequest\x12\x12\n" +
	"\x04cbor\x18\x01 \x01(\fR\x04cbor\"/\n" +
	"\x19PutIdentityObjectResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"q\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\fR\x06roomId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\fR\aspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\":\n" +
	"\tSpaceInfo\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\fR\aspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x10ListRoomsRequest\x12\x1d\n" +
	"\n" +
	"member_pub\x18\x01 \x01(\fR\tmemberPub\"j\n" +
	"\x11ListRoomsResponse\x12(\n" +
	"\x05rooms\x18\x01 \x03(\v2\x12.cairn.v1.RoomInfoR\x05rooms\x12+\n" +
	"\x06spaces\x18\x02 \x03(\v2\x13.cairn.v1.SpaceInfoR\x06spaces\"5\n" +
	"\x14ResolveSenderRequest\x12\x1d\n" +
	"\n" +
	"sender_pub\x18\x01 \x01(\fR\tsenderPub\"\xba\x01\n" +
	"\x15ResolveSenderResponse\x12-\n" +
	"\x12session_delegation\x18\x01 \x01(\fR\x11sessionDelegation\x12+\n" +
	"\x11device_delegation\x18\x02 \x01(\fR\x10deviceDelegation\x12 \n" +
	"\vattestation\x18\x03 \x01(\fR\vattestation\x12#\n" +
	"\rdevice_revoke\x18\x04 \x01(\fR\fdeviceRevoke*\xcc\x04\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04CHAT\x10\x01\x12\f\n" +
	"\bFILE_REF\x10\x02\x12\f\n" +
	"\bPRESENCE\x10\x03\x12\f\n" +
	"\bREACTION\x10\x04\x12\b\n" +
	"\x04EDIT\x10\x05\x12\n" +
	"\n" +
	"\x06DELETE\x10\x06\x12\x10\n" +
	"\fTASK_REQUEST\x10\n" +
	"\x12\x0f\n" +
	"\vTASK_UPDATE\x10\v\x12\n" +
	"\n" +
	"\x06NOTIFY\x10\f\x12\v\n" +
	"\aCOMMAND\x10\r\x12\x14\n" +
	"\x10APPROVAL_REQUEST\x10\x14\x12\x12\n" +
	"\x0eAPPROVAL_GRANT\x10\x15\x12\x11\n" +
	"\rAPPROVAL_DENY\x10\x16\x12\x15\n" +
	"\x11CREDENTIAL_MINTED\x10\x17\x12\t\n" +
	"\x05INLAY\x10\x1e\x12\x10\n" +
	"\fINLAY_UPDATE\x10\x1f\x12\x0f\n" +
	"\vINLAY_UNPIN\x10 \x12\x0f\n" +
	"\vINTERACTION\x10!\x12\x13\n" +
	"\x0fSIGNALING_OFFER\x10(\x12\x14\n" +
	"\x10SIGNALING_ANSWER\x10)\x12\x11\n" +
	"\rSIGNALING_ICE\x10*\x12\r\n" +
	"\tCALL_RING\x10+\x12\f\n" +
	"\bCALL_BYE\x10,\x12\x0e\n" +
	"\n" +
	"MEMBER_ADD\x102\x12\x11\n" +
	"\rMEMBER_REMOVE\x103\x12\x13\n" +
	"\x0fROOM_KEY_ROTATE\x104\x12\x10\n" +
	"\fSPACE_CREATE\x105\x12\x10\n" +
	"\fSPACE_UPDATE\x106\x12\x0f\n" +
	"\vROOM_CREATE\x107\x12\x18\n" +
	"\x14IDENTITY_ATTESTATION\x10<\x12\x15\n" +
	"\x11DEVICE_DELEGATION\x10=\x12\x11\n" +
	"\rDEVICE_REVOKE\x10>*\x90\x01\n" +
	"\rTransportHint\x12\x1e\n" +
	"\x1aTRANSPORT_HINT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSPORT_HINT_LAN\x10\x01\x12\x17\n" +
	"\x13TRANSPORT_HINT_MESH\x10\x02\x12\x16\n" +
	"\x12TRANSPORT_HINT_BLE\x10\x03\x12\x16\n" +
	"\x12TRANSPORT_HINT_ALL\x10\x042\x9f\x04\n" +
	"\fCairnService\x12D\n" +
	"\tSendEvent\x12\x1a.cairn.v1.SendEventRequest\x1a\x1b.cairn.v1.SendEventResponse\x125\n" +
	"\x04Sync\x12\x15.cairn.v1.SyncRequest\x1a\x16.cairn.v1.SyncResponse\x12>\n" +
	"\aHistory\x12\x18.cairn.v1.HistoryRequest\x1a\x19.cairn.v1.HistoryResponse\x12\\\n" +
	"\x11GetIdentityObject\x12\".cairn.v1.GetIdentityObjectRequest\x1a#.cairn.v1.GetIdentityObjectResponse\x12\\\n" +
	"\x11PutIdentityObject\x12\".cairn.v1.PutIdentityObjectRequest\x1a#.cairn.v1.PutIdentityObjectResponse\x12P\n" +
	"\rResolveSender\x12\x1e.cairn.v1.ResolveSenderRequest\x1a\x1f.cairn.v1.ResolveSenderResponse\x12D\n" +
	"\tListRooms\x12\x1a.cairn.v1.ListRoomsRequest\x1a\x1b.cairn.v1.ListRoomsResponseB6Z4github.com/geekgonecrazy/cairn/proto/cairnv1;cairnv1b\x06proto3"

var (
	file_cairn_proto_rawDescOnce sync.Once
	file_cairn_proto_rawDescData []byte
)

func file_cairn_proto_rawDescGZIP() []byte {
	file_cairn_proto_rawDescOnce.Do(func() {
		file_cairn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cairn_proto_rawDesc), len(file_cairn_proto_rawDesc)))
	})
	return file_cairn_proto_rawDescData
}

var file_cairn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cairn_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cairn_proto_goTypes = []any{
	(EventType)(0),                    // 0: cairn.v1.EventType
	(TransportHint)(0),                // 1: cairn.v1.TransportHint
	(*Event)(nil),                     // 2: cairn.v1.Event
	(*SendEventRequest)(nil),          // 3: cairn.v1.SendEventRequest
	(*SendEventResponse)(nil),         // 4: cairn.v1.SendEventResponse
	(*SyncRequest)(nil),               // 5: cairn.v1.SyncRequest
	(*SyncResponse)(nil),              // 6: cairn.v1.SyncResponse
	(*HistoryRequest)(nil),            // 7: cairn.v1.HistoryRequest
	(*HistoryResponse)(nil),           // 8: cairn.v1.HistoryResponse
	(*GetIdentityObjectRequest)(nil),  // 9: cairn.v1.GetIdentityObjectRequest
	(*GetIdentityObjectResponse)(nil), // 10: cairn.v1.GetIdentityObjectResponse
	(*PutIdentityObjectRequest)(nil),  // 11: cairn.v1.PutIdentityObjectRequest
	(*PutIdentityObjectResponse)(nil), // 12: cairn.v1.PutIdentityObjectResponse
	(*RoomInfo)(nil),                  // 13: cairn.v1.RoomInfo
	(*SpaceInfo)(nil),                 // 14: cairn.v1.SpaceInfo
	(*ListRoomsRequest)(nil),          // 15: cairn.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),         // 16: cairn.v1.ListRoomsResponse
	(*ResolveSenderRequest)(nil),      // 17: cairn.v1.ResolveSenderRequest
	(*ResolveSenderResponse)(nil),     // 18: cairn.v1.ResolveSenderResponse
}
var file_cairn_proto_depIdxs = []int32{
	0,  // 0: cairn.v1.Event.type:type_name -> cairn.v1.EventType
	2,  // 1: cairn.v1.SendEventRequest.event:type_name -> cairn.v1.Event
	1,  // 2: cairn.v1.SendEventRequest.hint:type_name -> cairn.v1.TransportHint
	2,  // 3: cairn.v1.SyncResponse.missing:type_name -> cairn.v1.Event
	2,  // 4: cairn.v1.HistoryResponse.events:type_name -> cairn.v1.Event
	13, // 5: cairn.v1.ListRoomsResponse.rooms:type_name -> cairn.v1.RoomInfo
	14, // 6: cairn.v1.ListRoomsResponse.spaces:type_name -> cairn.v1.SpaceInfo
	3,  // 7: cairn.v1.CairnService.SendEvent:input_type -> cairn.v1.SendEventRequest
	5,  // 8: cairn.v1.CairnService.Sync:input_type -> cairn.v1.SyncRequest
	7,  // 9: cairn.v1.CairnService.History:input_type -> cairn.v1.HistoryRequest
	9,  // 10: cairn.v1.CairnService.GetIdentityObject:input_type -> cairn.v1.GetIdentityObjectRequest
	11, // 11: cairn.v1.CairnService.PutIdentityObject:input_type -> cairn.v1.PutIdentityObjectRequest
	17, // 12: cairn.v1.CairnService.ResolveSender:input_type -> cairn.v1.ResolveSenderRequest
	15, // 13: cairn.v1.CairnService.ListRooms:input_type -> cairn.v1.ListRoomsRequest
	4,  // 14: cairn.v1.CairnService.SendEvent:output_type -> cairn.v1.SendEventResponse
	6,  // 15: cairn.v1.CairnService.Sync:output_type -> cairn.v1.SyncResponse
	8,  // 16: cairn.v1.CairnService.History:output_type -> cairn.v1.HistoryResponse
	10, // 17: cairn.v1.CairnService.GetIdentityObject:output_type -> cairn.v1.GetIdentityObjectResponse
	12, // 18: cairn.v1.CairnService.PutIdentityObject:output_type -> cairn.v1.PutIdentityObjectResponse
	18, // 19: cairn.v1.CairnService.ResolveSender:output_type -> cairn.v1.ResolveSenderResponse
	16, // 20: cairn.v1.CairnService.ListRooms:output_type -> cairn.v1.ListRoomsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cairn_proto_init() }
func file_cairn_proto_init() {
	if File_cairn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cairn_proto_rawDesc), len(file_cairn_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cairn_proto_goTypes,
		DependencyIndexes: file_cairn_proto_depIdxs,
		EnumInfos:         file_cairn_proto_enumTypes,
		MessageInfos:      file_cairn_proto_msgTypes,
	}.Build()
	File_cairn_proto = out.File
	file_cairn_proto_goTypes = nil
	file_cairn_proto_depIdxs = nil
}
